# suppress inspection "UnusedProperty" for whole file
server.port=8081
logging.level.guru.springframework=debug
spring.flyway.enabled=false
spring.docker.compose.enabled=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

spring.threads.virtual.enabled=true
# without virtual threads - 308 MB
# with virtual threads - 263 MB

management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true

# Analyzing spring security issues
# logging.level.org.springframework.security=trace

# DB Schema Generation
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata

#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create.sql

#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=drop-and-create.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=drop-and-create.sql